services:
  api:
    build:
      context: .
      dockerfile: ./apps/node.Dockerfile
      target: dev
      args:
        APP: api
    environment:
      KEYS_PATH: /home/node/root/keys.yaml
      LOG_LEVEL: ${LOG_LEVEL:-info}
      PORT: 9000
      TEMPORAL_ADDRESS: temporal:7233
    ports:
      - 9000:9000
    volumes:
      - ./apps/api:/home/node/root/apps/api
      - ./keys.yaml:/home/node/root/keys.yaml
    depends_on:
      temporal:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9000/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3

  ui:
    build:
      context: .
      dockerfile: ./apps/node.Dockerfile
      target: dev
      args:
        APP: ui
    environment:
      API_URL: http://api:9000
      LOG_LEVEL: ${LOG_LEVEL:-info}
      PORT: 9999
    ports:
      - 9999:9999
    volumes:
      - ./apps/ui:/home/node/root/apps/ui
    depends_on:
      api:
        condition: service_healthy
      worker:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9999 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3

  worker:
    build:
      context: .
      dockerfile: ./apps/golang.Dockerfile
      target: dev
      args:
        APP: worker
    environment:
      KEYS_PATH: /go/root/keys.yaml
      LOG_LEVEL: ${LOG_LEVEL:-info}
      TEMPORAL_ADDRESS: temporal:7233
    volumes:
      - ./apps/worker:/go/root/apps/worker
      - ./keys.yaml:/go/root/keys.yaml
    depends_on:
      temporal:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9000/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3

  # Example codec server, to decrypt payloads in the Temporal Web UI
  codec-server:
    image: ghcr.io/mrsimonemms/temporal-codec-server/golang
    environment:
      CORS_ALLOW_CREDS: false
      DISABLE_AUTH: true
      ENCRYPTION_TYPES: aes
      KEYS_PATH: /keys.yaml
      PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./keys.yaml:/keys.yaml

  temporal:
    image: temporalio/temporal
    ports:
      - 8233:8233
    command: >
      server start-dev --ip 0.0.0.0 --search-attribute ApplicationStatus=Keyword
      --search-attribute CurrentStep=Keyword --search-attribute HasOffer=Bool
      --search-attribute AwaitingExternalSignal=Bool --search-attribute
      WithinSLA=Bool --ui-codec-endpoint http://localhost:8080
    depends_on:
      # Not really a dependency of Temporal, but ensures everything starts up together
      codec-server:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "temporal operator cluster health" ]
      interval: 10s
      timeout: 10s
      retries: 3
